  # .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # 建议使用最新的稳定版本 tag
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: rustfmt
        name: rustfmt
        description: 'Check Rust code formatting with `cargo fmt`.'
        entry: cargo fmt --all
        language: rust
        types: [rust]
        pass_filenames: false

    -   id: clippy
        name: clippy
        description: 'Lint Rust code with `cargo clippy`.'
        entry: cargo clippy -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false
