[package]
name = "miko-core"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Core for miko"
repository = "https://github.com/miko-rs/miko"


[dependencies]
hyper = "1.7.0"
percent-encoding = "2.3.2"
